import type { AiPlaybookDefinition, AiPlaybookType } from './playbooks.types';

export const PLAYBOOK_DEFINITIONS: AiPlaybookDefinition[] = [
  {
    type: 'REFUND_SPIKE_DIAGNOSIS',
    title: '退款异常排查',
    description: '分析退款是否异常，并找出相关订单、商品、审批和处理建议。',
    category: 'RISK',
    estimatedMinutes: 2,
    enabled: true,
    objective: '判断退款是否异常，找出退款订单、商品、原因、审批和处理建议。',
    campaignDraftEnabled: false,
    actionKinds: ['VIEW_REPORT'],
    steps: [
      { id: 'refund-trend', title: '退款趋势', evidenceKeys: ['playbook_refund_total', 'playbook_refund_previous'] },
      { id: 'refund-orders', title: '退款订单', evidenceKeys: ['query_ev_refund_order_'] },
      { id: 'refund-items', title: '退款商品和订单类型', evidenceKeys: ['query_ev_refund_order_'] },
      { id: 'manager-approval', title: 'Manager Approval', evidenceKeys: ['playbook_manager_approval', 'query_ev_refund_order_'] },
      { id: 'refund-next-action', title: '处理建议', evidenceKeys: ['playbook_refund_total'] },
    ],
  },
  {
    type: 'SALES_DROP_DIAGNOSIS',
    title: '营业额下降排查',
    description: '拆解销售额、订单数、客单价、商品、堂食外带和顾客复购变化。',
    category: 'SALES',
    estimatedMinutes: 3,
    enabled: true,
    objective: '判断销售额是否下降，分析订单数、客单价、商品、顾客和桌台影响。',
    campaignDraftEnabled: true,
    actionKinds: ['VIEW_REPORT', 'CREATE_CAMPAIGN_DRAFT'],
    steps: [
      { id: 'sales-trend', title: '销售额对比', evidenceKeys: ['playbook_sales_net', 'playbook_sales_previous'] },
      { id: 'order-aov', title: '订单数和客单价', evidenceKeys: ['playbook_order_count', 'playbook_aov'] },
      { id: 'product-mix', title: '商品表现', evidenceKeys: ['playbook_top_products', 'playbook_low_products'] },
      { id: 'dine-in-takeaway', title: '堂食 / 外带结构', evidenceKeys: ['playbook_table_orders'] },
      { id: 'repeat-rate', title: '顾客复购', evidenceKeys: ['playbook_repeat_rate'] },
      { id: 'sales-next-action', title: '下步建议', evidenceKeys: ['playbook_sales_net'] },
    ],
  },
  {
    type: 'KITCHEN_OVERDUE_DIAGNOSIS',
    title: '后厨超时排查',
    description: '定位超时档口、超时菜品、加急票和 SLA 风险。',
    category: 'KITCHEN',
    estimatedMinutes: 2,
    enabled: true,
    objective: '找出超时档口、超时菜品、加急票、平均等待/制作时长，并给出处理建议。',
    campaignDraftEnabled: false,
    actionKinds: ['VIEW_KITCHEN'],
    steps: [
      { id: 'ticket-count', title: '超时厨房票', evidenceKeys: ['playbook_kitchen_sla'] },
      { id: 'station-overdue', title: '超时档口', evidenceKeys: ['playbook_overdue_stations'] },
      { id: 'overdue-products', title: '超时商品', evidenceKeys: ['query_ev_kitchen_ticket_'] },
      { id: 'rush-urgent', title: 'Urgent / Rush', evidenceKeys: ['playbook_kitchen_sla'] },
      { id: 'kitchen-next-action', title: '档口和菜单调整建议', evidenceKeys: ['playbook_kitchen_sla'] },
    ],
  },
  {
    type: 'DORMANT_CUSTOMER_REACTIVATION',
    title: '沉睡顾客召回',
    description: '识别沉睡顾客并推荐召回优惠和活动周期。',
    category: 'CUSTOMER',
    estimatedMinutes: 3,
    enabled: true,
    objective: '识别沉睡顾客，推荐召回策略，生成活动草稿。',
    campaignDraftEnabled: true,
    actionKinds: ['VIEW_CUSTOMER', 'CREATE_CAMPAIGN_DRAFT'],
    steps: [
      { id: 'dormant-count', title: '沉睡顾客数量', evidenceKeys: ['playbook_dormant_customers'] },
      { id: 'dormant-spend', title: '历史消费', evidenceKeys: ['query_ev_customer_detail_', 'playbook_top_customers'] },
      { id: 'discount-depth', title: '优惠力度', evidenceKeys: ['playbook_repeat_rate'] },
      { id: 'campaign-window', title: '活动周期', evidenceKeys: ['playbook_dormant_customers'] },
      { id: 'draft-campaign', title: '生成 Campaign Draft', evidenceKeys: ['playbook_dormant_customers'] },
    ],
  },
  {
    type: 'LOW_SELLING_PRODUCT_PROMO',
    title: '滞销商品促销',
    description: '找出低销量商品，判断是否适合轻量促销或搭配策略。',
    category: 'PRODUCT',
    estimatedMinutes: 3,
    enabled: true,
    objective: '识别低销量商品，推荐轻量促销或搭配策略。',
    campaignDraftEnabled: true,
    actionKinds: ['VIEW_PRODUCT', 'CREATE_CAMPAIGN_DRAFT'],
    steps: [
      { id: 'low-products', title: '低销量商品', evidenceKeys: ['playbook_low_products'] },
      { id: 'inactive-soldout', title: 'Inactive / Sold out', evidenceKeys: ['playbook_product_availability'] },
      { id: 'promo-fit', title: '促销适配', evidenceKeys: ['playbook_low_products'] },
      { id: 'discount-recommendation', title: '折扣或满减', evidenceKeys: ['playbook_sales_net'] },
      { id: 'draft-campaign', title: '生成 Campaign Draft', evidenceKeys: ['playbook_low_products'] },
    ],
  },
  {
    type: 'TOP_CUSTOMER_RETENTION',
    title: '高价值顾客维护',
    description: '识别高价值顾客并推荐专属奖励方案。',
    category: 'CUSTOMER',
    estimatedMinutes: 3,
    enabled: true,
    objective: '识别高价值顾客，推荐会员维护或专属活动。',
    campaignDraftEnabled: true,
    actionKinds: ['VIEW_CUSTOMER', 'CREATE_CAMPAIGN_DRAFT'],
    steps: [
      { id: 'top-customers', title: '高价值顾客', evidenceKeys: ['playbook_top_customers'] },
      { id: 'spend-orders', title: '消费金额和订单次数', evidenceKeys: ['playbook_top_customers'] },
      { id: 'repeat-analysis', title: '复购情况', evidenceKeys: ['playbook_repeat_rate'] },
      { id: 'reward-plan', title: '奖励方案', evidenceKeys: ['playbook_top_customers'] },
      { id: 'draft-campaign', title: '生成 Campaign Draft', evidenceKeys: ['playbook_top_customers'] },
    ],
  },
];

export function getPlaybookDefinition(type: string): AiPlaybookDefinition | null {
  return PLAYBOOK_DEFINITIONS.find((item) => item.type === type as AiPlaybookType) ?? null;
}
